### ISSUE TITLE
Tiny bit of documentation 

### ISSUE THREAD

**Issue by grubdragon** [ishank-juneja/email-with-spreadsheet#1]
Making this project dev-friendly would go a long way

**Comment by ishank-juneja** [comment]
Hi Aryan,
Thanks a lot for the suggestion. I will be adding detailed documentation soon (later this week or early next).
Perhaps would also be a good idea to make the interface plug and play in a manner that the code need not be edited by someone wishing to use the script.

**Comment by ishank-juneja** [comment]
The docs have been created now.
